spring:
  application:
    name: microservice-eureka
  config:
    import: optional:configserver:http://localhost:8088 # Search the config in Config server. Optional
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Eureka not self registered
    fetch-registry: false # No need to download the list of registered services
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/