spring:
  application:
    name: microservice-eureka
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Eureka not self registered
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:{$server.port}/eureka/